'
' Copyright 2021 Maxime "M4x1m3" FRIESS
' 
' This file is part of CoffeeLeaf.
'
' CoffeeLeaf is free software: you can redistribute it and/or modify
' it under the terms of the GNU Lesser General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' CoffeeLeaf is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU Lesser General Public License for more details.
'
' You should have received a copy of the GNU Lesser General Public License
' along with CoffeeLeaf.  If not, see <https://www.gnu.org/licenses/>.

@startuml
'https://plantuml.com/sequence-diagram
skinparam classFontStyle Bold
skinparam style strictuml

hide empty members

class UMLClass {
    -String name
}

class UMLPackage {
    +UMLPackage(String name, UMLPackage parent)
    +String getName()
    +UMLPackage findOrCreatePackage(String name)
    
    -String name
}

class UMLRootPackage extends UMLPackage {
    +UMLRootPackage()
}

class UMLModel {
    +UMLModel(String name)
    +addClass(Class clazz)
    
    -String name
    -UMLRootPackage rootpkg
}

UMLModel -> UMLRootPackage
UMLPackage *-> UMLPackage
UMLPackage *--> UMLClass

@enduml
